services:
  roka:
    image: roka
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - ./aspnet-keys:/root/.aspnet/DataProtection-Keys
